# Generated by Django 6.0.3 on 2026-03-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_cart_id_alter_category_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
