# Generated by Django 6.0.3 on 2026-04-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_product_carbon_footprint_alter_cart_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='waste_type',
            field=models.CharField(choices=[('Thermoplastics', 'Plastic - Thermoplastics'), ('Thermosetting Plastics', 'Plastic - Thermosetting Plastics'), ('Biodegradable Plastics', 'Plastic - Biodegradable Plastics'), ('Non-biodegradable Plastics', 'Plastic - Non-biodegradable Plastics'), ('IT Equipment', 'E-Waste - IT Equipment'), ('Telecommunication Devices', 'E-Waste - Telecommunication Devices'), ('Consumer Electronics', 'E-Waste - Consumer Electronics'), ('Lighting Equipment', 'E-Waste - Lighting Equipment'), ('Electrical Tools', 'E-Waste - Electrical Tools'), ('Medical Devices', 'E-Waste - Medical Devices'), ('Paper', 'Paper'), ('Metal', 'Metal'), ('Glass', 'Glass'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='register',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
