# Generated by Django 6.0.3 on 2026-04-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_cart_id_alter_category_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='sub_waste_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='waste_type',
            field=models.CharField(choices=[('Plastic', 'Plastic'), ('Electronic', 'Electronic/E-Waste'), ('Thermoplastics', 'Plastic - Thermoplastics'), ('Thermosetting Plastics', 'Plastic - Thermosetting Plastics'), ('Biodegradable Plastics', 'Plastic - Biodegradable Plastics'), ('Non-biodegradable Plastics', 'Plastic - Non-biodegradable Plastics'), ('IT Equipment', 'E-Waste - IT Equipment'), ('Telecommunication Devices', 'E-Waste - Telecommunication Devices'), ('Consumer Electronics', 'E-Waste - Consumer Electronics'), ('Lighting Equipment', 'E-Waste - Lighting Equipment'), ('Electrical Tools', 'E-Waste - Electrical Tools'), ('Medical Devices', 'E-Waste - Medical Devices'), ('Paper', 'Paper'), ('Cardboard', 'Paper - Cardboard'), ('Newspapers', 'Paper - Newspapers'), ('Office Paper', 'Paper - Office Paper'), ('Magazines', 'Paper - Magazines'), ('Books', 'Paper - Books'), ('Metal', 'Metal'), ('Aluminum Cans', 'Metal - Aluminum Cans'), ('Steel/Tin Cans', 'Metal - Steel/Tin Cans'), ('Scrap Metal', 'Metal - Scrap Metal'), ('Copper Wire', 'Metal - Copper Wire'), ('Glass', 'Glass'), ('Clear Glass', 'Glass - Clear Glass'), ('Green Glass', 'Glass - Green Glass'), ('Brown Glass', 'Glass - Brown Glass'), ('Other', 'Other')], max_length=50),
        ),
    ]
